name: cu-cpbs-7602
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _r-mutex=1.0.1=anacondar_1
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4409184_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py312hcae0c51_0
  - bwidget=1.10.1=hce30654_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_osx-arm64=1024.3=llvm21_1_haddd2d4_9
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h1b4d9a2_1
  - cfgv=3.5.0=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - clang=21.1.6=default_hf9bcbb7_0
  - clang-21=21.1.6=default_h489deba_0
  - clang_impl_osx-arm64=21.1.6=hdbf2fcc_25
  - clang_osx-arm64=21.1.6=h07b0088_25
  - clangxx=21.1.6=default_h36137df_0
  - clangxx_impl_osx-arm64=21.1.6=h7e475f0_25
  - clangxx_osx-arm64=21.1.6=h07b0088_25
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - compiler-rt=21.1.6=hce30654_0
  - compiler-rt21=21.1.6=h855ad52_0
  - compiler-rt21_osx-arm64=21.1.6=h2514db7_0
  - contourpy=1.3.3=py312h84eede6_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - curl=8.17.0=hdece5d2_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py312h56d30c9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py312h5748b74_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gfortran_impl_osx-arm64=14.3.0=h6d03799_1
  - gfortran_osx-arm64=14.3.0=h3c33bd0_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gsl=2.7=h6e638da_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=haf38c7b_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - identify=2.6.15=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isl=0.26=imath32_h347afa1_101
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h81bd7bf_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_1
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_highlight_selected_word=0.2.0=pyhd8ed1ab_1006
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.2.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jupytext=1.18.1=pyh80e38bb_0
  - kiwisolver=1.4.9=py312hd8c8125_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - ld64=955.13=h5d6df6c_9
  - ld64_osx-arm64=955.13=llvm21_1_hde6573c_9
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libblas=3.11.0=1_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.11.0=1_hb0561ab_openblas
  - libclang-cpp21.1=21.1.6=default_h73dfc95_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.6=hf598326_0
  - libcxx-devel=21.1.6=h6dc3340_0
  - libcxx-headers=21.1.6=h707e725_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran-devel_osx-arm64=14.3.0=hc965647_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.2=he69a767_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=1_hd9741b5_openblas
  - libllvm21=21.1.6=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.50=h280e0eb_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libxslt=1.1.43=hb2570ba_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - llvm-tools=21.1.6=h855ad52_0
  - llvm-tools-21=21.1.6=h91fd4e7_0
  - lxml=6.0.2=py312h447b5cf_2
  - make=4.4.1=hc9fafa5_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h5748b74_0
  - matplotlib=3.9.4=py312h1f38498_0
  - matplotlib-base=3.9.4=py312hdbc7e53_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclassic=1.3.3=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hc388f54_1
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbconvert-pandoc=7.16.6=h7d6f222_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - nodejs=22.19.0=h08a63db_0
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.2.6=py312h7c1f314_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py312hcb1e3ce_3
  - pandoc=3.8.2.1=hce30654_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py312h16e1670_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pre-commit=4.0.1=pyha770c72_1
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312h37e1c23_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py312h19bbe71_0
  - pyobjc-framework-cocoa=12.1=py312h1de3e18_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h18782d2_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h5748b74_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - r-askpass=1.2.1=r44h6168396_1
  - r-assertthat=0.2.1=r44hc72bb7e_6
  - r-backports=1.5.0=r44h6168396_2
  - r-base=4.4.3=h04a9237_5
  - r-base64enc=0.1_3=r44h6168396_1008
  - r-bit=4.6.0=r44h6168396_1
  - r-bit64=4.6.0_1=r44h6168396_1
  - r-blob=1.2.4=r44hc72bb7e_3
  - r-boot=1.3_32=r44hc72bb7e_1
  - r-broom=1.0.10=r44hc72bb7e_0
  - r-bslib=0.9.0=r44hc72bb7e_1
  - r-cachem=1.1.0=r44h6168396_2
  - r-callr=3.7.6=r44hc72bb7e_2
  - r-caret=7.0_1=r44h6168396_0
  - r-cellranger=1.1.0=r44hc72bb7e_1008
  - r-class=7.3_23=r44h6168396_1
  - r-cli=3.6.5=r44hc1cd577_1
  - r-clipr=0.8.0=r44hc72bb7e_4
  - r-clock=0.7.3=r44hc1cd577_1
  - r-cluster=2.1.8.1=r44hd097873_1
  - r-codetools=0.2_20=r44hc72bb7e_2
  - r-colorspace=2.1_2=r44h6168396_0
  - r-commonmark=2.0.0=r44h6168396_1
  - r-conflicted=1.2.0=r44h785f33e_3
  - r-cpp11=0.5.2=r44h785f33e_2
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-crul=1.6.0=r44hc72bb7e_1
  - r-curl=7.0.0=r44hbc3244a_1
  - r-data.table=1.17.8=r44hbd14437_1
  - r-dbi=1.2.3=r44hc72bb7e_2
  - r-dbplyr=2.5.1=r44hc72bb7e_1
  - r-diagram=1.6.5=r44ha770c72_4
  - r-digest=0.6.39=r44hc1cd577_0
  - r-dplyr=1.1.4=r44hc1cd577_2
  - r-dtplyr=1.3.2=r44hc72bb7e_1
  - r-e1071=1.7_16=r44hc1cd577_1
  - r-ellipsis=0.3.2=r44h6168396_4
  - r-essentials=4.4=r44hd8ed1ab_2006
  - r-evaluate=1.0.5=r44hc72bb7e_1
  - r-fansi=1.0.7=r44h6168396_0
  - r-farver=2.1.2=r44hc1cd577_2
  - r-fastmap=1.2.0=r44hc1cd577_2
  - r-fontawesome=0.5.3=r44hc72bb7e_1
  - r-forcats=1.0.1=r44hc72bb7e_0
  - r-foreach=1.5.2=r44hc72bb7e_4
  - r-foreign=0.8_90=r44h6168396_1
  - r-formatr=1.14=r44hc72bb7e_3
  - r-fs=1.6.6=r44hc1cd577_1
  - r-future=1.68.0=r44h785f33e_0
  - r-future.apply=1.20.0=r44hc72bb7e_1
  - r-gargle=1.6.0=r44h785f33e_1
  - r-generics=0.1.4=r44hc72bb7e_1
  - r-ggplot2=4.0.1=r44h785f33e_0
  - r-gistr=0.9.0=r44hc72bb7e_4
  - r-glmnet=4.1_10=r44hbf3f414_1
  - r-globals=0.18.0=r44hc72bb7e_1
  - r-glue=1.8.0=r44h6168396_1
  - r-googledrive=2.1.2=r44hc72bb7e_1
  - r-googlesheets4=1.1.2=r44h785f33e_1
  - r-gower=1.0.1=r44h6168396_3
  - r-gtable=0.3.6=r44hc72bb7e_1
  - r-hardhat=1.4.2=r44hc72bb7e_1
  - r-haven=2.5.5=r44h82072fd_1
  - r-hexbin=1.28.5=r44hd097873_1
  - r-highr=0.11=r44hc72bb7e_2
  - r-hms=1.1.4=r44hc72bb7e_0
  - r-htmltools=0.5.8.1=r44hc1cd577_2
  - r-htmlwidgets=1.6.4=r44h785f33e_4
  - r-httpcode=0.3.0=r44hf450f58_5
  - r-httpuv=1.6.16=r44h82072fd_1
  - r-httr=1.4.7=r44hc72bb7e_2
  - r-ids=1.0.1=r44hc72bb7e_5
  - r-ipred=0.9_15=r44hd097873_2
  - r-irdisplay=1.1=r44hd8ed1ab_4
  - r-irkernel=1.3.2=r44h785f33e_3
  - r-isoband=0.2.7=r44hc1cd577_4
  - r-iterators=1.0.14=r44hc72bb7e_4
  - r-jquerylib=0.1.4=r44hc72bb7e_4
  - r-jsonlite=2.0.0=r44h6168396_1
  - r-kableextra=1.4.0=r44hc72bb7e_2
  - r-kernsmooth=2.23_26=r44hc8a44f4_1
  - r-knitr=1.50=r44hc72bb7e_1
  - r-labeling=0.4.3=r44hc72bb7e_2
  - r-later=1.4.4=r44hc1cd577_1
  - r-lattice=0.22_7=r44h6168396_1
  - r-lava=1.8.2=r44hc72bb7e_0
  - r-lazyeval=0.2.2=r44h6168396_6
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-listenv=0.10.0=r44hc72bb7e_0
  - r-lobstr=1.1.3=r44hc1cd577_0
  - r-lubridate=1.9.4=r44h6168396_1
  - r-magrittr=2.0.4=r44h6168396_0
  - r-maps=3.4.3=r44h6168396_1
  - r-mass=7.3_65=r44h6168396_0
  - r-matrix=1.7_4=r44hb2d3ebe_1
  - r-memoise=2.0.1=r44hc72bb7e_4
  - r-mgcv=1.9_4=r44hc952b19_0
  - r-mime=0.13=r44h6168396_1
  - r-modelmetrics=1.2.2.2=r44hb601842_5
  - r-modelr=0.1.11=r44hc72bb7e_3
  - r-munsell=0.5.1=r44hc72bb7e_2
  - r-nlme=3.1_168=r44hd097873_1
  - r-nnet=7.3_20=r44h6168396_1
  - r-numderiv=2016.8_1.1=r44hc72bb7e_7
  - r-openssl=2.3.4=r44h7a56cc5_0
  - r-otel=0.2.0=r44hc72bb7e_1
  - r-parallelly=1.45.1=r44h6168396_1
  - r-pbdzmq=0.3_14=r44h350048c_1
  - r-pillar=1.11.1=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_5
  - r-plyr=1.8.9=r44hc1cd577_3
  - r-prettyunits=1.2.0=r44hc72bb7e_2
  - r-proc=1.19.0.1=r44hc1cd577_1
  - r-processx=3.8.6=r44h6168396_1
  - r-prodlim=2025.04.28=r44hc1cd577_1
  - r-progress=1.2.3=r44hc72bb7e_2
  - r-progressr=0.18.0=r44hc72bb7e_0
  - r-promises=1.5.0=r44hc72bb7e_1
  - r-proxy=0.4_27=r44h6168396_4
  - r-pryr=0.1.6=r44hc1cd577_3
  - r-ps=1.9.1=r44h6168396_1
  - r-purrr=1.2.0=r44h6168396_0
  - r-quantmod=0.4.28=r44hc72bb7e_1
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-ragg=1.5.0=r44hf65f6a8_1
  - r-randomforest=4.7_1.2=r44hd097873_1
  - r-rappdirs=0.3.3=r44h6168396_4
  - r-rbokeh=0.5.2=r44hc72bb7e_5
  - r-rcolorbrewer=1.1_3=r44h785f33e_4
  - r-rcpp=1.1.0=r44hc1cd577_1
  - r-rcppeigen=0.3.4.0.2=r44hd057375_1
  - r-readr=2.1.6=r44hc1cd577_0
  - r-readxl=1.4.5=r44hf730888_1
  - r-recipes=1.3.1=r44hc72bb7e_1
  - r-recommended=4.4=r44hd8ed1ab_1008
  - r-rematch=2.0.0=r44hc72bb7e_2
  - r-rematch2=2.1.2=r44hc72bb7e_5
  - r-repr=1.1.7=r44h785f33e_2
  - r-reprex=2.1.1=r44hc72bb7e_2
  - r-reshape2=1.4.5=r44hc1cd577_0
  - r-rlang=1.1.6=r44hc1cd577_1
  - r-rmarkdown=2.30=r44hc72bb7e_0
  - r-rpart=4.1.24=r44h6168396_1
  - r-rstudioapi=0.17.1=r44hc72bb7e_1
  - r-rvest=1.0.5=r44hc72bb7e_1
  - r-s7=0.2.1=r44h6168396_0
  - r-sass=0.4.10=r44hc1cd577_1
  - r-scales=1.4.0=r44hc72bb7e_1
  - r-selectr=0.5_0=r44hc72bb7e_0
  - r-shape=1.4.6.1=r44ha770c72_2
  - r-shiny=1.11.1=r44h785f33e_1
  - r-sourcetools=0.1.7_1=r44hc1cd577_3
  - r-sparsevctrs=0.3.4=r44h6168396_1
  - r-spatial=7.3_18=r44h6168396_1
  - r-squarem=2021.1=r44hc72bb7e_4
  - r-stringi=1.8.7=r44he9eb878_1
  - r-stringr=1.6.0=r44h785f33e_0
  - r-survival=3.8_3=r44h6168396_1
  - r-svglite=2.2.2=r44h5a62864_0
  - r-sys=3.4.3=r44h6168396_1
  - r-systemfonts=1.3.1=r44h288a467_0
  - r-textshaping=1.0.4=r44h288a467_0
  - r-tibble=3.3.0=r44h6168396_1
  - r-tidyr=1.3.1=r44hc1cd577_2
  - r-tidyselect=1.2.1=r44hc72bb7e_2
  - r-tidyverse=2.0.0=r44h785f33e_3
  - r-timechange=0.3.0=r44hc1cd577_2
  - r-timedate=4051.111=r44hc72bb7e_0
  - r-tinytex=0.58=r44hc72bb7e_0
  - r-triebeard=0.4.1=r44hc1cd577_4
  - r-ttr=0.24.4=r44h6168396_2
  - r-tzdb=0.5.0=r44hc1cd577_2
  - r-urltools=1.7.3.1=r44hc1cd577_1
  - r-utf8=1.2.6=r44h6168396_1
  - r-uuid=1.2_1=r44h6168396_1
  - r-vctrs=0.6.5=r44hc1cd577_2
  - r-viridislite=0.4.2=r44hc72bb7e_3
  - r-vroom=1.6.6=r44hc1cd577_0
  - r-webshot=0.5.5=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_1
  - r-xfun=0.54=r44hc1cd577_0
  - r-xml2=1.5.0=r44h7a605a7_0
  - r-xtable=1.8_4=r44hc72bb7e_7
  - r-xts=0.14.1=r44h6168396_1
  - r-yaml=2.3.10=r44h6168396_1
  - r-zoo=1.8_14=r44h6168396_1
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.29.0=py312h6ef9ec0_0
  - rpy2=3.6.4=py312r44hd99f0fb_1
  - scikit-learn=1.5.2=py312h387f99c_1
  - scipy=1.14.1=py312h6bb24ec_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py312ha11c99a_1
  - tapi=1300.6.5=h03f4b80_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.0=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - tktable=2.10=h3c7de25_7
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py312h4409184_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - ukkonen=1.0.1=py312ha0dd364_6
  - unicodedata2=17.0.0=py312h4409184_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py312h37e1c23_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
prefix: /opt/anaconda3/envs/cu-cpbs-7602
